language: python

sudo: false

env:
    - TARGET=unit

python:
    - "3.4"

services:
    - mongodb
    - elasticsearch
    - redis-server

cache:
  directories:
    - $HOME/.cache/pip

install:
    - if [ "${TARGET}" = "unit" ] ; then
        pip install -r requirements.txt && pip install coveralls==1.0a2;
      fi

script:
    - if [ "${TARGET}" = "unit" ]; then
        flake8;
        nosetests --with-coverage --cover-package=superdesk ;
      fi

after_script:
    - killall -9 python
