language: python

sudo: required
dist: trusty

services:
    - redis-server
    - elasticsearch

matrix:
    include:
        - env: ELASTIC2X
          python: "3.5"
          addons:
              apt:
                  sources:
                      - elasticsearch-2.x
                      - mongodb-3.0-precise
                  packages:
                      - elasticsearch
                      - mongodb-org-server

        - env: ELASTIC17
          python: "3.4"
          addons:
              apt:
                  sources:
                      - elasticsearch-1.7
                      - mongodb-3.0-precise
                  packages:
                      - elasticsearch
                      - mongodb-org-server


        - env: ELASTIC17
          python: "3.5"
          addons:
              apt:
                  sources:
                      - elasticsearch-1.7
                      - mongodb-3.0-precise
                  packages:
                      - elasticsearch
                      - mongodb-org-server

cache:
  - pip

install:
    - pip install .
    - pip install -r dev-requirements.txt

before_script: >
    df -h
    && sudo sed -i 's\enabled: true\enabled: false\' /etc/mongod.conf
    && sudo service mongod restart

script:
    - flake8
    - nosetests --logging-level=ERROR
    - behave --format progress2 --logging-level=ERROR
